spring:
  application:
    name: service-notificacao

  config:
    import: file:.env[.properties]

  server:
    port: 0

  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_HOST}
      register-with-eureka: true
      fetch-registry: true

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000