spring:
  application:
    name: service-email

  config:
    import: file:.env[.properties]

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${MYSQL_DATABASE}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

server:
  port: 0

  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_HOST}
      register-with-eureka: true
      fetch-registry: true

