spring:
  application:
    name: service-email

  datasource:
    url: jdbc:mysql://localhost:3306/empiricus_email?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root

#    config:
#      import: file:.env[.properties]

server:
  port: 0

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
      register-with-eureka: true
      fetch-registry: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ivopivoteste@gmail.com
    password: sktevgkzftrooylq

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000