spring:
  application:
      name: service-discovery

  config:
    import: file:.env[.properties]

server:
  port: ${EUREKA_SERVER_PORT}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_HOST}

  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    server:
      eviction-interval-timer-in-ms: 60000
