spring:
  application:
    name: service-gateWay

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: service-usuario
          uri: lb://service-usuario
          predicates:
            - Path=/api/usuario/**

        - id: service-email
          uri: lb://service-email
          predicates:
            - Path=/api/email/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/