spring:
  application:
    name: service-gateWay

  config:
    import: file:.env[.properties]

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  main:
    allow-bean-definition-overriding: true

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 86400000

server:
  port: ${GATEWAY_PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOST}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
