spring:
  application:
    name: service-gateWay

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true



  main:
    allow-bean-definition-overriding: true

jwt:
  secret: "UmaSenhaAi"
  expiration-ms: 86400000

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000